package Tema6ArraysList.Ejercicio11Restaurante;

public class NombresRestaurantes {

    public static String nombreAleatorio() {
        String[] arrayNombres = {
            "El rincón enchilado",
            "Tacos picantes El Quetzal",
            "Fajitas aztecas",
            "Puro sabor mexicano",
            "Fogones mexicanos",
            "Cocinando con Tequila",
            "México en tu casa",
            "Comiendo con Mariachis",
            "Antojo de burritos",
            "Nachos de Monterrey",
            "The best ceviche",
            "Perú criollo",
            "Peruvian sweets",
            "Lima's fish",
            "El pollo peruano",
            "Peruvian wishes",
            "Comiendo Lima",
            "Sabor del Vinicunca",
            "El ceviche encantado",
            "Bocado de Perú",
            "Croquetas pa' ti",
            "Comer & Beber",
            "La buena tortilla",
            "Cervezas y tapas bravas",
            "Marinada & vino",
            "Paella en casa",
            "Gusto ibérico",
            "Sabores de la tierra",
            "Solo de tortillas",
            "Only Spaghetti",
            "Pizza per tutti",
            "Dolce Italia",
            "La Mozzarella",
            "Fresh Pasta & Pizza",
            "Massa para la mesa",
            "Torre di pizza",
            "Morso di Italia",
            "Shibuya's Ramen",
            "Ginza Sushi",
            "Tokyo dinner",
            "Japanese delicious food",
            "Yokohama's meal",
            "Gyoza in Ginza",
            "Oishī Asakusa",
            "Curry in Japan",
            "Cuídate de un bocado",
            "Come y vive",
            "Freshly foodie",
            "Funny vegetables",
            "Health & Food",
            "Fast and healthy cooking",
            "Healthy & tasty",
            "Natural food",
            "Eat without stress",
            "Pita Pan & Pita",
            "Beer y Creer",
            "La Concha de la Lora",
            "Hungry Simpson",
            "FaceFood",
            "TerePizza",
            "MARmitako",
            "Churrosko",
            "La Tapilla Sixtina",
            "Restaurante y Bar Vader",
            "Churrasic Park",
            "Rich vegetables",
            "Vegan foodies",
            "The best vegetables",
            "Fogones verdes",
            "Vida vegana",
            "Veggie Chef",
            "Magic Salad",
            "La Ensaladera",
            "Vegan's Garden",
            "Organicly green",
        };

        int posicionAleatoria = (int) (Math.random() * arrayNombres.length);

        return arrayNombres[posicionAleatoria];
    }
}
